export const editorThemes: { label: string; value: string; bg: string }[] = [
  { label: "Monokai", value: "monokai", bg: "#272822" },
  { label: "Dracula", value: "dracula", bg: "#282a36" },
  { label: "One Dark", value: "one_dark", bg: "#282c34" },
  { label: "Github", value: "github", bg: "#fff" },
  { label: "Github Dark", value: "github_dark", bg: "#24292e" },
  { label: "Tomorrow", value: "tomorrow", bg: "#FFFFFF" },
  { label: "Kuroir", value: "kuroir", bg: "#E8E9E8" },
  { label: "Twilight", value: "twilight", bg: "#141414" },
  { label: "Xcode", value: "xcode", bg: "#FFFFFF" },
  { label: "Textmate", value: "textmate", bg: "#FFFFFF" },
  { label: "Solarized Dark", value: "solarized_dark", bg: "#002B36" },
  { label: "Solarized Light", value: "solarized_light", bg: "#FDF6E3" },
  { label: "Terminal", value: "terminal", bg: "#000" },
  { label: "Tomorrow Night", value: "tomorrow_night", bg: "#1D1F21" },
  { label: "Tomorrow Night Blue", value: "tomorrow_night_blue", bg: "#002451" },
];
