export const editorThemes: { label: string; value: string; bg: string }[] = [
  { label: "GitHub Dark", value: "github-dark", bg: "#0d1117" },
  { label: "GitHub Light", value: "github-light", bg: "#ffffff" },
  { label: "Dracula", value: "dracula", bg: "#282a36" },
  { label: "Monokai", value: "monokai", bg: "#272822" },
  { label: "One Dark Pro", value: "one-dark-pro", bg: "#282c34" },
  { label: "Catppuccin Mocha", value: "catppuccin-mocha", bg: "#1e1e2e" },
  { label: "Catppuccin Latte", value: "catppuccin-latte", bg: "#eff1f5" },
  { label: "Nord", value: "nord", bg: "#2e3440" },
  { label: "Rose Pine", value: "rose-pine", bg: "#191724" },
  { label: "Rose Pine Dawn", value: "rose-pine-dawn", bg: "#faf4ed" },
  { label: "Tokyo Night", value: "tokyo-night", bg: "#1a1b26" },
  { label: "Night Owl", value: "night-owl", bg: "#011627" },
  { label: "Poimandres", value: "poimandres", bg: "#1b1e28" },
  { label: "Vitesse Dark", value: "vitesse-dark", bg: "#121212" },
  { label: "Vitesse Light", value: "vitesse-light", bg: "#ffffff" },
  { label: "Aurora X", value: "aurora-x", bg: "#07090f" },
  { label: "Synthwave '84", value: "synthwave-84", bg: "#262335" },
  { label: "Solarized Dark", value: "solarized-dark", bg: "#002b36" },
  { label: "Min Dark", value: "min-dark", bg: "#1f1f1f" },
  { label: "Min Light", value: "min-light", bg: "#f8f8f8" },
];
